---
abstract: 'Bash completion for perlbrew'
author:
  - 'Rob Hoelz <rob@hoelz.ro>'
configure_requires:
  Module::Build: 0.36
dynamic_config: 0
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bash-Completion-Plugins-perlbrew
provides:
  Bash::Completion::Plugins::perlbrew:
    file: lib/Bash/Completion/Plugins/perlbrew.pm
    version: 0.01
requires:
  Bash::Completion: 0.001
  perl: v5.10.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
